name: 'Validate Pull Request Title'
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull Request Title Validation
        uses: skimit/validate-pull-request-title-github-action@v1.1.0
        with:
          pr-title: "${{ github.event.pull_request.title }}"
