version: "3.9"
services:
  web:
    container_name: ${PROJECT_NAME}
    build:
      context: ..
      dockerfile: docker/Dev.Dockerfile
    env_file: ../.env
    volumes:
      - ..:/usr/src/app
      - venvs:/venvs
      - app_volume:/usr/src/circleci

volumes:
  app_volume:
  venvs:
