name: 'Validate Project Dependencies Licenses'
on: push

jobs:
  validate-project-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Dependency License Checker
        uses: skimit/pypi-license-checker-github-action@v1.2.3
